.TH GOBBY 1 "August 17, 2006"
.\" Please adjust this date whenever revising the manpage.
.\" For manpage-specific macros: see man(7).
.SH NAME
.B gobby
\- a collaborative text editor
.SH SYNOPSIS
.B gobby
.RI [ options ]
.RI [ file(s) ]
.SH DESCRIPTION
.B gobby
is an editor which allows to edit text documents and source files
collaboratively over a network. Changes to the documents are syncronised
instantly to the other clients. 
.PP
.SH OPTIONS
.TP
\fB\-j\fR, \fB\-\-join\fR=\fIHOST\fR:\fIPORT\fR
Joins the obby session on the specified host.
.TP
\fB\-n\fR, \fB\-\-new\-instance\fR
Forces a new instance of Gobby to be created.
.TP
.B file(s)
Files passed on the command line will be opened within Gobby. If there is
already a Gobby instance running they will be opened therein, otherwise
a new hosted session will be created automatically.
.PP
.SH AUTHOR
.B gobby
was written by the 0x539 dev group <crew@0x539.de>.
