#!/bin/sh
for file in code/resources/ui/*.ui; do
        intltool-extract --type="gettext/glade" $file
        sed -i -e 's/char \*s = //' ${file}.h
        git add ${file}.h
done

grep --binary-files=without-match "_(" code -R | \
	sed -e 's/:.*//' | uniq | sort > po/POTFILES.in
echo gobby-0.5.desktop.in >> po/POTFILES.in
