N_("_Preferences");
N_("Help");
N_("About");
N_("_Quit");
N_("_File");
N_("_New...");
N_("_Open...");
N_("Open _Location...");
N_("_Save");
N_("Save _As...");
N_("Save All");
N_("Export As _HTML...");
N_("Connect _To Server...");
N_("_Close");
N_("_Edit");
N_("_Undo");
N_("_Redo");
N_("Cut");
N_("_Copy");
N_("Paste");
N_("_Find...");
N_("Find Ne_xt");
N_("_Find Pre_vious");
N_("Find And Re_place...");
N_("Go To _Line");
N_("_View");
N_("Reset User Colors");
N_("Fullscreen");
N_("Zoom In");
N_("Zoom Out");
N_("View Tool Bar");
N_("View Status Bar");
N_("View Document Browser");
N_("View Chat");
N_("View Document User List");
N_("View Chat User List");
N_("_Highlight Mode");
N_("None");
